language: python
sudo: false
python:
- '3.5'
before_install:
- openssl aes-256-cbc -K $encrypted_c77138175719_key -iv $encrypted_c77138175719_iv
  -in onshapepy_conf.yaml.enc -out ~\/onshapepy_conf.yaml -d
- export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
install:
- pip install pipenv
- pipenv install --dev
- gem install html-proofer
script:
- pipenv run pytest --cov=./
- cd docs
- pipenv run make html
- pipenv run make doctest
- htmlproofer _build/html --allow_hash_href --file_ignore "_build/html/search.html"
- cd ..
after_success:
- pipenv run codecov
deploy:
- provider: pypi
  user: "$PYPI_USERNAME"
  password: "$PYPI_PASSWORD"
  on:
    tags: true
  distributions: sdist
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: docs/_build/html
  target-branch: gh-pages
  on:
    tags: true
