language: python
sudo: false
python:
- '3.5'
before_install:
 - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
 - openssl aes-256-cbc -K $encrypted_0b30f5022c54_key -iv $encrypted_0b30f5022c54_iv
  -in creds.json.enc -out creds.json -d
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
install:
  - pip install pipenv
  - pipenv install
  - gem install html-proofer
script:
  - pipenv run pytest --cov=./
  - cd docs # build the docs... should be moved to before_deploy?
  - make html
  - make doctest
  - htmlproofer _build/html --allow_hash_href --file_ignore "_build/html/search.html"
  - cd ..
after_success:
  - pipenv run codecov
deploy:
  - provider: pypi
    user: "$PYPI_USERNAME"
    password: "$PYPI_PASSWORD"
    on:
      tags: true
    distributions: sdist
  - provider: pages # Deploy to to gh-pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    local-dir: docs/_build/html
    target-branch: gh-pages
    on:
      tags: true
